
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/sleeper-data/*"
  to = "https://raw.githubusercontent.com/dajuns5567/FFL-trade-finder/sleeper-data/data/sleeper/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/site-v27"
  status = 200
  force = true

[[redirects]]
  from = "/api/update"
  to = "/.netlify/functions/update"
  status = 200
  force = true

[[redirects]]
  from = "/api/picks"
  to = "/.netlify/functions/picks"
  status = 200
  force = true
