(()=>{
let pvPosFilter='ALL';
function topMode(){const b=document.querySelector('#playerValueFilter button:not(.secondary)');return b?.dataset?.valueFilter||'ALL'}
function original(row){const title=row.querySelector('b'),meta=row.querySelector('small');if(title&&title.dataset.pvBaseTitle==null)title.dataset.pvBaseTitle=title.textContent||'';if(meta&&meta.dataset.pvBaseMeta==null)meta.dataset.pvBaseMeta=meta.textContent||'';return{title,meta}}
function restoreAll(){document.querySelectorAll('#rankings .valueRow19').forEach(row=>{const{title,meta}=original(row);if(title)title.textContent=title.dataset.pvBaseTitle||'';if(meta)meta.textContent=meta.dataset.pvBaseMeta||'';row.style.display=''})}
function ensurePosFilter(){const top=document.getElementById('playerValueFilter');if(!top)return null;let wrap=document.getElementById('playerPositionFilter');if(!wrap){wrap=document.createElement('div');wrap.id='playerPositionFilter';wrap.style.cssText='display:none;gap:8px;flex-wrap:wrap;margin:-4px 0 12px';wrap.innerHTML='<button type="button" class="small" data-pos-filter="ALL">All Offense</button><button type="button" class="secondary small" data-pos-filter="QB">QB</button><button type="button" class="secondary small" data-pos-filter="RB">RB</button><button type="button" class="secondary small" data-pos-filter="WR">WR</button><button type="button" class="secondary small" data-pos-filter="TE">TE</button>';top.insertAdjacentElement('afterend',wrap);wrap.addEventListener('click',e=>{const b=e.target.closest('button[data-pos-filter]');if(!b)return;pvPosFilter=b.dataset.posFilter;apply()})}wrap.style.display=topMode()==='OFFENSE'?'flex':'none';wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('secondary',b.dataset.posFilter!==pvPosFilter));return wrap}
function apply(){const sec=document.getElementById('rankings');if(!sec)return;restoreAll();ensurePosFilter();const mode=topMode();if(mode==='ALL')return;const host=mode==='OFFENSE'?document.getElementById('allOffense'):document.getElementById('allDefense');if(!host)return;let rows=[...host.querySelectorAll('.valueRow19')];if(mode==='OFFENSE'&&pvPosFilter!=='ALL'){rows.forEach(row=>{const{meta}=original(row),src=meta?.dataset?.pvBaseMeta||'';if(!src.startsWith(pvPosFilter+' •'))row.style.display='none'})}const visible=rows.filter(row=>row.style.display!=='none');const label=mode==='DEFENSE'?'defense':(pvPosFilter==='ALL'?'offense':pvPosFilter.toLowerCase());visible.forEach((row,i)=>{const n=i+1,{title,meta}=original(row);if(title){const name=(title.dataset.pvBaseTitle||'').replace(/^\d+\.\s*/,'');title.textContent=`${n}. ${name}`}if(meta)meta.textContent=(meta.dataset.pvBaseMeta||'').replace(/overall #\d+/,`${label} #${n}`)})}
function schedule(){setTimeout(apply,0)}
document.addEventListener('click',e=>{if(e.target.closest('#playerValueFilter button[data-value-filter]')){if(e.target.closest('[data-value-filter="OFFENSE"]'))pvPosFilter='ALL';schedule()}if(e.target.closest('.tabs button[data-tab="rankings"]'))schedule()});
document.addEventListener('input',e=>{if(e.target?.id==='allValueSearch')schedule()});
const prevRenderAll=renderAll;renderAll=function(){prevRenderAll();schedule()};
setTimeout(apply,0);
})();
