(()=>{
let pvPosFilter='ALL',pvRookiesOnly=false;
function topMode(){const b=document.querySelector('#playerValueFilter button:not(.secondary)');return b?.dataset?.valueFilter||'ALL'}
function norm(s){return String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function original(row){const title=row.querySelector('b'),meta=row.querySelector('small');if(title&&title.dataset.pvBaseTitle==null)title.dataset.pvBaseTitle=title.textContent||'';if(meta&&meta.dataset.pvBaseMeta==null)meta.dataset.pvBaseMeta=meta.textContent||'';return{title,meta}}
function restoreAll(){document.querySelectorAll('#rankings .valueRow19').forEach(row=>{const{title,meta}=original(row);if(title)title.textContent=title.dataset.pvBaseTitle||'';if(meta)meta.textContent=meta.dataset.pvBaseMeta||'';row.style.display=''})}
function ensureControls(){const top=document.getElementById('playerValueFilter');if(!top)return;let rookie=document.getElementById('playerRookieFilter');if(!rookie){rookie=document.createElement('button');rookie.id='playerRookieFilter';rookie.type='button';rookie.className='secondary small';rookie.textContent='Rookies';top.appendChild(rookie);rookie.addEventListener('click',()=>{pvRookiesOnly=!pvRookiesOnly;apply()})}rookie.classList.toggle('secondary',!pvRookiesOnly);let wrap=document.getElementById('playerPositionFilter');if(!wrap){wrap=document.createElement('div');wrap.id='playerPositionFilter';wrap.style.cssText='display:none;gap:8px;flex-wrap:wrap;margin:-4px 0 12px';wrap.innerHTML='<button type="button" class="small" data-pos-filter="ALL">All Offense</button><button type="button" class="secondary small" data-pos-filter="QB">QB</button><button type="button" class="secondary small" data-pos-filter="RB">RB</button><button type="button" class="secondary small" data-pos-filter="WR">WR</button><button type="button" class="secondary small" data-pos-filter="TE">TE</button>';top.insertAdjacentElement('afterend',wrap);wrap.addEventListener('click',e=>{const b=e.target.closest('button[data-pos-filter]');if(!b)return;pvPosFilter=b.dataset.posFilter;apply()})}wrap.style.display=topMode()==='OFFENSE'?'flex':'none';wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('secondary',b.dataset.posFilter!==pvPosFilter))}
function bindIds(){const q=norm(document.getElementById('allValueSearch')?.value||''),ranked=ensureMaster();for(const [hostId,isIdp] of [['allOffense',false],['allDefense',true]]){const host=document.getElementById(hostId);if(!host)continue;const players=ranked.filter(z=>(groupPos(z.x)==='IDP')===isIdp&&(!q||norm(playerName(z.x.id)).includes(q)));[...host.querySelectorAll('.valueRow19')].forEach((row,i)=>{row.dataset.pvPlayerId=String(players[i]?.x?.id||'')})}}
function isRookie(row){const id=row.dataset.pvPlayerId,p=state.players?.[String(id)]||{};return Number(p.years_exp)===0}
function apply(){const sec=document.getElementById('rankings');if(!sec)return;restoreAll();ensureControls();bindIds();const mode=topMode(),off=document.getElementById('allOffense'),def=document.getElementById('allDefense');if(!off||!def)return;const allRows=[...sec.querySelectorAll('.valueRow19')];for(const row of allRows){const inOff=!!row.closest('#allOffense'),inDef=!!row.closest('#allDefense');let keep=true;if(mode==='OFFENSE')keep=inOff;else if(mode==='DEFENSE')keep=inDef;if(keep&&mode==='OFFENSE'&&pvPosFilter!=='ALL'){const src=original(row).meta?.dataset?.pvBaseMeta||'';keep=src.startsWith(pvPosFilter+' •')}if(keep&&pvRookiesOnly)keep=isRookie(row);row.style.display=keep?'':'none'}if(mode==='ALL'){if(pvRookiesOnly){for(const host of [off,def]){[...host.querySelectorAll('.valueRow19')].filter(r=>r.style.display!=='none').forEach(row=>{const{title,meta}=original(row);if(title)title.textContent=title.dataset.pvBaseTitle||'';if(meta)meta.textContent=meta.dataset.pvBaseMeta||''})}}return}const host=mode==='OFFENSE'?off:def,visible=[...host.querySelectorAll('.valueRow19')].filter(r=>r.style.display!=='none');let label=mode==='DEFENSE'?'defense':(pvPosFilter==='ALL'?'offense':pvPosFilter.toLowerCase());if(pvRookiesOnly)label='rookie '+label;visible.forEach((row,i)=>{const n=i+1,{title,meta}=original(row);if(title){const name=(title.dataset.pvBaseTitle||'').replace(/^\d+\.\s*/,'');title.textContent=`${n}. ${name}`}if(meta)meta.textContent=(meta.dataset.pvBaseMeta||'').replace(/overall #\d+/,`${label} #${n}`)})}
function schedule(){setTimeout(apply,0)}
document.addEventListener('click',e=>{if(e.target.closest('#playerValueFilter button[data-value-filter]')){if(e.target.closest('[data-value-filter="OFFENSE"]'))pvPosFilter='ALL';schedule()}if(e.target.closest('.tabs button[data-tab="rankings"]'))schedule()});
document.addEventListener('input',e=>{if(e.target?.id==='allValueSearch')schedule()});
const prevRenderAll=renderAll;renderAll=function(){prevRenderAll();schedule()};
setTimeout(apply,0);
})();
