(()=>{
function norm19(s){return String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function rosterOwner(id){return state.allAssets.find(x=>x.type==='player'&&String(x.id)===String(id))?.owner??null}
function globalPlayerRows(q){const n=norm19(q);if(!n)return[];return Object.entries(state.players||{}).filter(([id,p])=>p?.fantasy_positions?.length&&norm19(playerName(id)).includes(n)).map(([id])=>({id,owner:rosterOwner(id)})).filter(x=>x.owner!=null).sort((a,b)=>baseValue({type:'player',id:b.id})-baseValue({type:'player',id:a.id})).slice(0,20)}
function displayScore19(v){const n=Number(v);return Number.isFinite(n)?Math.max(1,Math.round(n*4)):1}
window.displayValueScore=displayScore19;
function ensureGlobalEvalSearch(side){const sel=document.getElementById('eval'+side);if(!sel||document.getElementById('evalGlobalSearch'+side))return;const wrap=document.createElement('div');wrap.innerHTML=`<label>Search any league player</label><input id="evalGlobalSearch${side}" type="search" placeholder="Search any player before choosing a team…" autocomplete="off"><div id="evalGlobalResults${side}" class="tiny" style="margin:6px 0 10px"></div>`;sel.parentNode.insertBefore(wrap,sel);const input=wrap.querySelector('input'),results=wrap.querySelector(`#evalGlobalResults${side}`);input.addEventListener('input',()=>{const rows=globalPlayerRows(input.value);results.innerHTML=rows.map(r=>`<button type="button" class="secondary small" data-pid="${r.id}" data-owner="${r.owner}" style="margin:2px">${playerName(r.id)} • ${teamName(r.owner)}</button>`).join('')});results.addEventListener('click',e=>{const b=e.target.closest('button[data-pid]');if(!b)return;sel.value=String(b.dataset.owner);sel.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>{const asset=state.allAssets.find(x=>x.type==='player'&&String(x.id)===String(b.dataset.pid));if(asset){state['assets'+side]=[{...asset}];renderAssets(side);if(typeof window.renderEvalChooser==='function')window.renderEvalChooser(side)}},0);input.value=playerName(b.dataset.pid);results.innerHTML=''})}
function ensureFinderGlobalSearch(){const sel=document.getElementById('findTeam');if(!sel||document.getElementById('finderGlobalSearch'))return;const wrap=document.createElement('div');wrap.innerHTML=`<label>Search any league player</label><input id="finderGlobalSearch" type="search" placeholder="Search any player…" autocomplete="off"><div id="finderGlobalResults" class="tiny" style="margin:6px 0"></div>`;sel.parentNode.insertBefore(wrap,sel);const input=wrap.querySelector('input'),results=wrap.querySelector('#finderGlobalResults');input.addEventListener('input',()=>{const rows=globalPlayerRows(input.value);results.innerHTML=rows.map(r=>`<button type="button" class="secondary small" data-pid="${r.id}" data-owner="${r.owner}" style="margin:2px">${playerName(r.id)} • ${teamName(r.owner)}</button>`).join('')});results.addEventListener('click',e=>{const b=e.target.closest('button[data-pid]');if(!b)return;sel.value=String(b.dataset.owner);sel.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>{const box=[...document.querySelectorAll('.shopCheck')].find(c=>String(c._asset?.id)===String(b.dataset.pid));if(box){box.checked=true;box.scrollIntoView({block:'center'})}},0);input.value=playerName(b.dataset.pid);results.innerHTML=''})}
function historyLabel19(id){
 const isIdp=groupPos({type:'player',id})==='IDP';
 if(isIdp&&typeof window.idpScoringAudit==='function'){
  const a=window.idpScoringAudit(id);if(!a||!a.qualifyingSeasons)return'No qualifying imported Sleeper scoring history';
  return `${a.ppg.toFixed(1)} PPG • ${a.qualifyingSeasons} qualifying season${a.qualifyingSeasons===1?'':'s'} • confidence ${(a.confidence*100).toFixed(0)}% • scoring component ${a.productionValue}`;
 }
 if(!isIdp&&typeof window.offenseScoringAudit==='function'){
  const a=window.offenseScoringAudit(id);if(!a||!a.qualifyingSeasons)return'No qualifying imported Sleeper PPR scoring history';
  return `${a.ppg.toFixed(1)} PPR PPG • ${a.qualifyingSeasons} qualifying season${a.qualifyingSeasons===1?'':'s'} • confidence ${(a.confidence*100).toFixed(0)}% • scoring component ${a.productionValue??'n/a'}`;
 }
 const rs=rawScore(id);if(!rs.seasons)return'No qualifying 8+ game season in the production window';return `${rs.ppg.toFixed(1)} PPG • ${rs.seasons} qualifying season${rs.seasons===1?'':'s'} • confidence ${(rs.confidence*100).toFixed(0)}%`;
}
function ensureAllValues(){const sec=document.getElementById('rankings');if(!sec)return;sec.innerHTML=`<div class="card"><h2>All player values</h2><p class="muted">Every player with a consensus or rostered value. TV is the model value used by the trade engine. Score is the same value on a 4× display scale for easier visual separation; it does not change rankings or trade math. IDP history uses imported Sleeper league scoring. Offensive history uses imported Sleeper PPR scoring when available.</p><input id="allValueSearch" type="search" placeholder="Search all values…" style="margin-bottom:10px"><div class="grid"><div><h3>Offense</h3><div id="allOffense"></div></div><div><h3>Defense</h3><div id="allDefense"></div></div></div></div>`;const input=sec.querySelector('#allValueSearch');input.addEventListener('input',renderAllValues);renderAllValues()}
function valueRow(z,i){const x=z.x,m=playerRankValue(x),p=state.players?.[x.id]||{},team=p.team||'FA';return `<div class="asset valueRow19" data-name="${norm19(playerName(x.id))}"><div><b>${i}. ${playerName(x.id)}</b><br><small>${groupPos(x)} • ${team} • CV ${m.consensus??'fallback'} • TV ${m.value} • Score ${displayScore19(m.value)} • overall #${m.rank}</small><br><small class="muted">${historyLabel19(x.id)}</small></div></div>`}
function renderAllValues(){const off=document.getElementById('allOffense'),def=document.getElementById('allDefense');if(!off||!def)return;const q=norm19(document.getElementById('allValueSearch')?.value||''),ranked=ensureMaster();const o=ranked.filter(z=>groupPos(z.x)!=='IDP'&&(!q||norm19(playerName(z.x.id)).includes(q))),d=ranked.filter(z=>groupPos(z.x)==='IDP'&&(!q||norm19(playerName(z.x.id)).includes(q)));off.innerHTML=o.map((z,i)=>valueRow(z,i+1)).join('')||"<div class='empty'>No matching offensive players.</div>";def.innerHTML=d.map((z,i)=>valueRow(z,i+1)).join('')||"<div class='empty'>No matching IDPs.</div>"}
function patchUI(){ensureGlobalEvalSearch('A');ensureGlobalEvalSearch('B');ensureFinderGlobalSearch();if(document.getElementById('rankings'))ensureAllValues()}
const prev=renderAll;renderAll=function(){prev();setTimeout(patchUI,0)};
document.addEventListener('click',e=>{const b=e.target.closest('.tabs button[data-tab="rankings"]');if(b)setTimeout(ensureAllValues,0)});
setTimeout(patchUI,0);
})();
