(()=>{
const priorMaster28=masterRankings;
const num28=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp28=(lo,x,hi)=>Math.max(lo,Math.min(hi,x));
function audit28(id){return typeof window.idpScoringAudit==='function'?window.idpScoringAudit(id):null}
function pct28(arr,x){if(!arr.length||!Number.isFinite(x))return .5;let below=0,equal=0;for(const v of arr){if(v<x)below++;else if(v===x)equal++}return clamp28(.01,(below+.5*equal)/arr.length,.99)}
let pop28=null,statsRef28=null,planKey28='';
function population28(){const key=JSON.stringify(state.sleeperHistory?.weightPlan||{});if(pop28&&statsRef28===state.stats&&planKey28===key)return pop28;const rows=[];for(const id of Object.keys(state.players||{})){if(groupPos({type:'player',id})!=='IDP')continue;const a=audit28(id),ppg=num28(a?.ppg);if(ppg==null||Number(a?.qualifyingSeasons)<=0)continue;rows.push({id,ppg})}pop28={ppg:rows.map(r=>r.ppg)};statsRef28=state.stats;planKey28=key;return pop28}
function profile28(id){const a=audit28(id),d=population28(),ppg=num28(a?.ppg),seasons=Number(a?.qualifyingSeasons)||0,conf=clamp28(0,num28(a?.confidence)??0,1),spike=clamp28(.01,(num28(a?.spikePercentile)??50)/100,.99),tackle=clamp28(.01,(num28(a?.tacklePercentile)??50)/100,.99),ppgPct=pct28(d.ppg,ppg);const impact=.64*ppgPct+.24*spike+.12*tackle;const sample=seasons>=3?1:seasons===2?.80:seasons===1?.42:0,evidence=conf*sample;return{a,ppg,seasons,conf,ppgPct,spike,tackle,impact,evidence}}
function translation28(p){if(p.ppg==null||p.seasons<=0||p.conf<=0)return{mult:1,tier:'ordinary'};let tier='ordinary',target=1;if(p.ppgPct>=.97&&p.impact>=.88){tier='exceptional';target=1.82}else if(p.ppgPct>=.92&&p.impact>=.82){tier='elite';target=1.60}else if(p.ppgPct>=.86&&p.impact>=.76){tier='high-impact';target=1.36}else if(p.ppgPct>=.79&&p.impact>=.70){tier='strong';target=1.16}const mult=1+(target-1)*p.evidence;return{mult:clamp28(1,mult,1.82),tier}}
function marketRail28(id,z,p,mult){const c=num28(state.consensusComposite?.byId?.[id])??num28(z.consensus)??0;if(c<=0)return mult;if(c<150&&p.evidence<.75)return Math.min(mult,1.10);if(c<250&&p.evidence>=.90&&p.ppgPct>=.90)return Math.max(mult,1.20);return mult}
function rebuild28(z){if(groupPos(z.x)!=='IDP')return z;const id=String(z.x.id),p=profile28(id),tr=translation28(p),old=num28(z.production?.idpPopulationMultiplierV51)??1;const base=Math.max(1,z.value/Math.max(.5,old));let mult=marketRail28(id,z,p,tr.mult);const c=num28(state.consensusComposite?.byId?.[id])??num28(z.consensus)??0;if(c>=700&&p.ppgPct<.79)mult=Math.min(mult,1.01);const next=Math.max(1,Math.round(base*mult));return{...z,value:next,production:{...(z.production||{}),idpCalibrationV53:true,idpPopulationTierV53:tr.tier,idpPopulationMultiplierV53:Number(mult.toFixed(3)),idpPpgPercentileV53:Number((p.ppgPct*100).toFixed(1)),idpImpactIndexV53:Number((p.impact*100).toFixed(1)),idpEvidenceV53:Number(p.evidence.toFixed(3)),idpSpikePercentileV53:Number((p.spike*100).toFixed(1)),idpTacklePercentileV53:Number((p.tackle*100).toFixed(1)),idpModelWeights:{consensus:.40,scoringLookback:.40,otherLeagueDynastyContext:.20}}}}
masterRankings=function(){return priorMaster28().map(rebuild28).sort((a,b)=>b.value-a.value)};
ensureMaster=function(){return masterRankCache||(masterRankCache=masterRankings())};
playerRankValue=function(x){const arr=ensureMaster(),i=arr.findIndex(z=>String(z.x.id)===String(x.id));if(i<0)return{rank:999,value:1,tier:9,consensus:null,context:null};const z=arr[i],rank=i+1,tiers=[12,24,48,80,120,180,260,400,9999];let tier=tiers.findIndex(m=>rank<=m);if(tier<0)tier=8;return{rank,value:z.value,tier:tier+1,consensus:z.consensus,context:z.context}};
baseValue=function(x){if(x.type==='pick')return pickValue(x);if(valueCache.has(x.id))return valueCache.get(x.id);const v=playerRankValue(x).value;valueCache.set(x.id,v);return v};
masterRankCache=null;valueCache.clear();fitCache.clear();stageCache.clear();
})();
