(()=>{
const priorMaster27=masterRankings;
const num27=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp27=(lo,x,hi)=>Math.max(lo,Math.min(hi,x));
function audit27(id){return typeof window.idpScoringAudit==='function'?window.idpScoringAudit(id):null}
function pct27(arr,x){if(!arr.length||!Number.isFinite(x))return .5;let below=0,equal=0;for(const v of arr){if(v<x)below++;else if(v===x)equal++}return clamp27(.01,(below+.5*equal)/arr.length,.99)}
let pop27=null,statsRef27=null,planKey27='';
function population27(){const key=JSON.stringify(state.sleeperHistory?.weightPlan||{});if(pop27&&statsRef27===state.stats&&planKey27===key)return pop27;const rows=[];for(const id of Object.keys(state.players||{})){if(groupPos({type:'player',id})!=='IDP')continue;const a=audit27(id),ppg=num27(a?.ppg);if(ppg==null||Number(a?.qualifyingSeasons)<=0)continue;rows.push({id,ppg})}pop27={ppg:rows.map(r=>r.ppg)};statsRef27=state.stats;planKey27=key;return pop27}
function profile27(id){const a=audit27(id),d=population27(),ppg=num27(a?.ppg),seasons=Number(a?.qualifyingSeasons)||0,conf=clamp27(0,num27(a?.confidence)??0,1),spike=clamp27(.01,(num27(a?.spikePercentile)??50)/100,.99),tackle=clamp27(.01,(num27(a?.tacklePercentile)??50)/100,.99),ppgPct=pct27(d.ppg,ppg);const impact=.60*ppgPct+.25*spike+.15*tackle;const sample=seasons>=3?1:seasons===2?.78:seasons===1?.45:0,evidence=conf*sample;return{a,ppg,seasons,conf,ppgPct,spike,tackle,impact,evidence}}
function translation27(p){if(p.ppg==null||p.seasons<=0||p.conf<=0)return{mult:1,tier:'ordinary'};let tier='ordinary',target=1;if(p.ppgPct>=.97&&p.impact>=.90){tier='exceptional';target=1.68}else if(p.ppgPct>=.92&&p.impact>=.84){tier='elite';target=1.48}else if(p.ppgPct>=.86&&p.impact>=.77){tier='high-impact';target=1.30}else if(p.ppgPct>=.78&&p.impact>=.70){tier='strong';target=1.14}const mult=1+(target-1)*p.evidence;return{mult:clamp27(1,mult,1.68),tier}}
function consensusRail27(id,z,p,mult){const c=num27(state.consensusComposite?.byId?.[id])??num27(z.consensus)??0;if(c<=0)return mult;if(c>=700)return Math.max(mult,1.04);if(c<150&&p.evidence<.75)return Math.min(mult,1.12);return mult}
function rebuild27(z){if(groupPos(z.x)!=='IDP')return z;const id=String(z.x.id),p=profile27(id),tr=translation27(p),old=num27(z.production?.idpCombinedMultiplierV50)??1;base=Math.max(1,z.value/Math.max(.5,old));let mult=consensusRail27(id,z,p,tr.mult);if(tr.tier==='ordinary'&&Math.abs(mult-1)<.001&&Math.abs(old-1)<.001)return z;const next=Math.max(1,Math.round(base*mult));return{...z,value:next,production:{...(z.production||{}),idpCalibrationV51:true,idpPopulationTierV51:tr.tier,idpPopulationMultiplierV51:Number(mult.toFixed(3)),idpPpgPercentileV51:Number((p.ppgPct*100).toFixed(1)),idpImpactIndexV51:Number((p.impact*100).toFixed(1)),idpEvidenceV51:Number(p.evidence.toFixed(3)),idpSpikePercentileV51:Number((p.spike*100).toFixed(1)),idpTacklePercentileV51:Number((p.tackle*100).toFixed(1)),idpModelWeights:{consensus:.40,scoringLookback:.40,otherLeagueDynastyContext:.20}}}}
masterRankings=function(){return priorMaster27().map(rebuild27).sort((a,b)=>b.value-a.value)};
ensureMaster=function(){return masterRankCache||(masterRankCache=masterRankings())};
playerRankValue=function(x){const arr=ensureMaster(),i=arr.findIndex(z=>String(z.x.id)===String(x.id));if(i<0)return{rank:999,value:1,tier:9,consensus:null,context:null};const z=arr[i],rank=i+1,tiers=[12,24,48,80,120,180,260,400,9999];let tier=tiers.findIndex(m=>rank<=m);if(tier<0)tier=8;return{rank,value:z.value,tier:tier+1,consensus:z.consensus,context:z.context}};
baseValue=function(x){if(x.type==='pick')return pickValue(x);if(valueCache.has(x.id))return valueCache.get(x.id);const v=playerRankValue(x).value;valueCache.set(x.id,v);return v};
masterRankCache=null;valueCache.clear();fitCache.clear();stageCache.clear();
})();
